--display information regarding the amount of disk activity generated by Transact-SQL statements
--logical reads  -- Number of pages read from the data cache. 
--physical reads  -- Number of pages read from disk. 

SET STATISTICS IO ON

-- Your SQL Script

SET STATISTICS IO OFF 